
%.wav:  %.ogg
	oggdec $<

all:	32857_zimm_heartbeat_regular_trimmed.wav \
	be_the_wumpus.wav \
	breath2.wav \
	drips2.wav \
	fall_with_impact.wav \
	fast_breath.wav \
	level_eight.wav \
	level_five.wav \
	level_four.wav \
	level_nine.wav \
	level_one.wav \
	level_seven.wav \
	level_six.wav \
	level_ten.wav \
	level_three.wav \
	level_two.wav \
	loud_splash1.wav \
	medium_splash1.wav \
	medium_splash2.wav \
	medium_splash3.wav \
	medium_splash4.wav \
	medium_splash5.wav \
	medium_splash6.wav \
	medium_splash7.wav \
	medium_splash8.wav \
	rocks1.wav \
	rocks2.wav \
	rocks3.wav \
	rocks4.wav \
	rocks5.wav \
	rocks6.wav \
	rocks7.wav \
	rocks8.wav \
	running_water.wav \
	scary_wumpus_music.wav \
	wumpus_dines.wav \
	wumpus_intro_music.wav \
	wumpus_roar.wav \
	oh_shit_oh_shit.wav \
	hello.wav \
	fast_breath1.wav \
	fast_breath2.wav \
	huuuuuh.wav \
	mild_surprise_breath.wav \
	arrow_clatter.wav \
	arrow_whoosh.wav \
	qubodup_fall_with_impact.wav \
	qubodup_fuck_fuck.wav \
	qubodup_hello.wav \
	qubodup_jesus_christ1.wav \
	qubodup_jesus_christ2.wav \
	qubodup_mild_surprise1.wav \
	qubodup_mild_surprise2.wav \
	qubodup_normal_breath1.wav \
	qubodup_normal_breath2.wav \
	qubodup_normal_breath3.wav \
	qubodup_oh_god2.wav \
	qubodup_oh_god.wav \
	qubodup_shit_oh_shit.wav \
	qubodup_what_was_that.wav \
	qubodup_who_is_there.wav \
	qubodup_wumpus_dines.wav \
	alphahog_breath1.wav \
	alphahog_breath2.wav \
	alphahog_breath3.wav \
	alphahog_breath5.wav \
	alphahog_breath6.wav \
	alphahog_breath4.wav \
	alphahog_fall_with_impact.wav \
	alphahog_hello2.wav \
	alphahog_hello_is_someone_there.wav \
	alphahog_huuuh.wav \
	alphahog_oh_sheeit_sheeit.wav \
	alphahog_ohshit.wav \
	alphahog_wumpus_dine.wav

clean:
	/bin/rm -f *.wav

