
%.wav:  %.ogg
	oggdec $<

all:	32857_zimm_heartbeat_regular_trimmed.wav \
	be_the_wumpus.wav \
	breath2.wav \
	drips2.wav \
	fall_with_impact.wav \
	fast_breath.wav \
	level_eight.wav \
	level_five.wav \
	level_four.wav \
	level_nine.wav \
	level_one.wav \
	level_seven.wav \
	level_six.wav \
	level_ten.wav \
	level_three.wav \
	level_two.wav \
	loud_splash1.wav \
	medium_splash1.wav \
	medium_splash2.wav \
	medium_splash3.wav \
	medium_splash4.wav \
	medium_splash5.wav \
	medium_splash6.wav \
	medium_splash7.wav \
	medium_splash8.wav \
	rocks1.wav \
	rocks2.wav \
	rocks3.wav \
	rocks4.wav \
	rocks5.wav \
	rocks6.wav \
	rocks7.wav \
	rocks8.wav \
	running_water.wav \
	scary_wumpus_music.wav \
	wumpus_dines.wav \
	wumpus_intro_music.wav \
	wumpus_roar.wav

clean:
	/bin/rm -f *.wav

