.TH BETHEWUMPUS "6" "May 2007" "bethewumpus" "Games"
.SH NAME
bethewumpus \- An audio-only game in which you are a blind, 
cave-dwelling wumpus who subsists on meals of unlucky cave
wanderers.
.SH SYNOPSIS
.B bethewumpus [ --sounddevice n ] [ --version ]
.SH DESCRIPTION
.\" Add any additional description here
.PP
You may have hunted the wumpus back in the 1970's 
before they became an endangered species.  Now you
can be the wumpus.  Headphones are strongly recommended,
and a dual stick gamepad, such as a Logitech Dual Action
Rumble (the only kind I've tried) is required.  
.PP 
Sneak up on your prey, and eat them.
.SH Options:
.TP
\fB\--sounddevice n\fR
Use alternate sound device n, where n is an integer.  
By default, bethewumpus uses the "default" sound device as 
estimated by the PortAudio library, which is 0.  
You can specify other numbers if you have other sound cards, or
a multichannel sound card.
.TP
\fB\--version\fR
Print the program's version number and exit.
.SH Controls:
.PP 
Just play with the buttons and joysticks while listening with
headphones, you'll get it.
.SH AUTHOR
Written by Stephen M. Cameron, (inspired by the game "In the Pit" by Studio Hunty,
which I've never played -- I've only read about it.)
.SH SEE ALSO
http://bethewumpus.sourceforge.net 
.br
